gamelog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from dashboard.views import DashboardView


urlpatterns = patterns('',
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'', include('authorisation.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^players/', include('players.urls')),
    url(r'^groups/', include('groups.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

games/urls.py
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.GameListView.as_view(), name='game_list'),
    url(r'^create/$', views.GameCreateView.as_view(), name='game_create'),
    url(r'^plays/$', views.GamePlayListView.as_view(), name='game_play_list'),
    url(r'^plays/create/$', views.GamePlayCreateView.as_view(), name='game_play_create'),
    url(r'^plays/(?P<pk>\d+)/$', views.GamePlayDetailView.as_view(), name='game_play_detail'),
    url(r'^plays/(?P<pk>\d+)/edit/$', views.GamePlayUpdateView.as_view(), name='game_play_update'),
    url(r'^(?P<slug>.+)/plays/create/$', views.GamePlayCreateFromGameView.as_view(), name='game_play_create_from_game'),
    url(r'^(?P<slug>.+)/edit/$', views.GameUpdateView.as_view(), name='game_update'),
    url(r'^(?P<slug>.+)/$', views.GameDetailView.as_view(), name='game_detail'),
)

players/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

from autoslug import AutoSlugField


class Player(models.Model):
    user = models.ForeignKey(get_user_model(), blank=True, null=True)
    slug = AutoSlugField(
        populate_from='fullname',
        unique=True,
    )

    # Fields if this isn't tied to a user
    _first_name = models.CharField(
        max_length=255, blank=True, null=True,
        verbose_name='First name',
    )
    _last_name = models.CharField(
        max_length=255, blank=True, null=True,
        verbose_name='Last name',
    )

    class Meta:
        permissions = (
            ('view_all_players', 'View all players',),
        )

    @property
    def fullname(self):
        if self.first_name and self.last_name:
            return u'%s %s' % (self.first_name, self.last_name)
        else:
            return self.user.username

    def get_absolute_url(self):
        return reverse('player_detail', args=(), kwargs={'slug': self.slug})

    def get_from_self_or_user(self, field_name):
        if self.user:
            inst = self.user
        else:
            inst = self
            field_name = '_%s' % field_name

        return getattr(inst, field_name)

    @property
    def first_name(self):
        return self.get_from_self_or_user('first_name')

    @property
    def last_name(self):
        return self.get_from_self_or_user('last_name')

    def __unicode__(self):
        if self.first_name:
            return u'%s %s' % (self.first_name, self.last_name)
        else:
            return self.slug

    def get_current_rating_for_game(self, game):
        try:
            ratings = self.rating_set.filter(game_play__game=game)
            ratings = ratings.order_by('-game_play__played_at', '-pk')

            return ratings[0].rating
        except IndexError:
            return settings.INITIAL_ELO_RATING

    def get_current_group_rating_for_game(self, game, group):
        try:
            group_ratings = self.grouprating_set.filter(group=group, game_play__game=game)
            group_ratings = group_ratings.order_by('-game_play__played_at', '-pk')

            return group_ratings[0].rating
        except IndexError:
            return self.get_current_rating_for_game(game)


@receiver(post_save, sender=get_user_model())
def create_player_from_user(sender, instance, created, **kwargs):
    if created:
        Player.objects.create(
            user=instance,
        )

gamelog/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Bogogger</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet" href="/static/css/normalize.css">
        <link rel="stylesheet" href="/static/css/main.css">
        <script src="/static/js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body class="{% block body_class %}{% endblock %}">

        <header class="clearfix">
            <h1>
                <a href="{% url 'dashboard' %}">Bogogger</a>
                <sup>Beta</sup>
            </h1>
            <nav class="clearfix">
                <ul>
                    <li><a href="{% url 'game_list' %}">Games</a></li>
                    {% if 'view_plays' in perms %}
                    <li><a href="{% url 'game_play_list' %}">Plays</a></li>
                    {% endif %}
                    <li><a href="{% url 'player_list' %}">Players</a></li>
                    <li><a href="{% url 'player_group_list' %}">Groups</a></li>
                </ul>
            </nav>

            {% if user.is_authenticated %}
            <form class="sign-out-form" action="{% url 'sign_out' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Sign Out</button>
            </form>
            {% endif %}
        </header>

        <main>
            {% block content %}
            {% endblock %}
        </main>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/static/js/vendor/jquery-2.0.2.min.js"><\/script>')</script>
        <script src="/static/js/plugins.js"></script>
        <script src="/static/js/main.js"></script>
    </body>
</html>